dataset_folder: "bags/dataset/"
output_folder: "bags/evaluation_results/"
omit_names: ["pa", "results"]

summary_metrics: 
  - "GT Mean Speed"
  - "Est Mean Speed"
  - "GT Median Speed"
  - "Est Median Speed"
  - "GT Speed Variance"
  - "Est Speed Variance"
  - "GT Max Speed"
  - "Est Max Speed"
  - "GT Mean Angular Speed"
  - "Est Mean Angular Speed"
  - "GT Median Angular Speed"
  - "Est Median Angular Speed"
  - "GT Angular Speed Variance"
  - "Est Angular Speed Variance"
  - "GT Max Angular Speed"
  - "Est Max Angular Speed"
  - "Time Duration"
  - "GT Final Dist to Goal"
  - "Est Final Dist to Goal"
  - "Est Drift"
  - "Mean APE"
  - "Median APE"
  - "Std APE"
  - "Min APE"
  - "Max APE"
  - "RMSE APE"
  - "Mean RPE"
  - "Median RPE"
  - "Std RPE"
  - "Min RPE"
  - "Max RPE"
  - "RMSE RPE"
  - "mean wobble"
  - "mean blur varlap"
  - "mean blur freq ratio"
  - "median tracking residual"
  - "p95 tracking residual"
  - "GT Travelled Distance"
  - "Est Travelled Distance"
  - "GT Path length"
  - "Est Path length"
  - "mean n matches"
  - "mean n features in frame 0"
  - "mean n features in frame 1"
  - "n map points"

subtables: 
  - dynamic_metrics:
    - "GT Mean Speed"
    - "Est Mean Speed"
    - "GT Median Speed"
    - "Est Median Speed"
    - "GT Speed Variance"
    - "Est Speed Variance"
    - "GT Max Speed"
    - "Est Max Speed"
    - "GT Mean Angular Speed"
    - "Est Mean Angular Speed"
    - "GT Angular Speed Variance"
    - "Est Angular Speed Variance"
    - "GT Median Angular Speed"
    - "Est Median Angular Speed"
    - "GT Max Angular Speed"
    - "Est Max Angular Speed"

  - geometric_metrics:
    - "GT Travelled Distance"
    - "Est Travelled Distance"
    - "GT Path length"
    - "Est Path length"
    - "GT Final Dist to Goal"
    - "Est Final Dist to Goal"
    - "Est Drift"
    - "Time Duration"

  - vision_metrics:
    - "Mean APE"
    - "Median APE"
    - "Std APE"
    - "Min APE"
    - "Max APE"
    - "RMSE APE"
    - "Mean RPE"
    - "Median RPE"
    - "Std RPE"
    - "Min RPE"
    - "Max RPE"
    - "RMSE RPE"
    - "mean n matches"
    - "mean n features in frame 0"
    - "mean n features in frame 1"
    - "mean wobble"
    - "mean blur varlap"
    - "mean blur freq ratio"
    - "median tracking residual"
    - "p95 tracking residual"
    - "n map points"
